/**
 * Source-plane entry of the vendored Typert protocol.
 *
 * `lib/` is the published build of the package — `lib/index.js` and `lib/types/index.d.ts` — and the real
 * surface of this package; see VENDOR.md. This file only puts the package in the
 * planes the Typert generator needs: it makes the manifest export target map to an
 * existing source file, and it keeps the protocol symbols owned by a registered
 * project of the workspace aggregate tsconfig.
 *
 * Generated by `npm run sync-shims` — do not hand-edit the lists below.
 */
export { TYPERT_OWNED_VALUE, bindTypertRemote, isRemoteJsonValue, isRemoteUplinkItem, isTypertOwnedValue, isTypertRemoteSegment, Remote, RemoteError, remoteErrorOf, remoteMethods, RemoteScope, typertOwnedValue, TypertRemoteService } from '../lib/types/index.js'
export type {
  InvocationDescriptor,
  InvocationParameterDescriptor,
  InvocationSourceLocation,
  PeerId,
  PeerScope,
  RemoteErrorCode,
  RemoteErrorDetailsMap,
  RemoteFailure,
  RemoteInvocation,
  RemoteInvocationMarker,
  RemoteMethodMarker,
  RemoteMethodOptions,
  RemoteResult,
  RemoteStream,
  RemoteStreamHandle,
  TypertClientContextAdapter,
  TypertClientEventListener,
  TypertClientRemote,
  TypertCodec,
  TypertContext,
  TypertContextMap,
  TypertContextRegistry,
  TypertContextWire,
  TypertDisposer,
  TypertForwardableEvent,
  TypertForwardableEventEntry,
  TypertGatewayBinding,
  TypertGatewayBindingOptions,
  TypertHostContextAdapter,
  TypertHostContextResolver,
  TypertLocalRegistry,
  TypertLookup,
  TypertLookupDefinition,
  TypertLookupHost,
  TypertLookupMap,
  TypertLookupProvider,
  TypertLookupRegistry,
  TypertLookupResolver,
  TypertLookupWire,
  TypertOwnedValue,
  TypertRegistryChange,
  TypertRegistryListener,
  TypertRemoteContribution,
  TypertRemoteEvent,
  TypertRemoteEventSelection,
  TypertRemoteMap,
  TypertRemoteNamespace,
  TypertRemoteNamespaceMap,
  TypertRemoteRegistry,
  TypertRemoteScopeApi,
  TypertRemoteScopeMap,
  TypertRemoteScopeNamespace,
  TypertSchema,
} from '../lib/types/index.js'

// Deliberately not re-exported: `TypertRegistryContract`. Its `Context.typert` member
// is installed by the launcher, not by a plugin, so this package must not read as the
// provider of that service to the Typert generator (which would then require a
// `./typert` artifact here). See VENDOR.md.
